global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"


scrape_configs:
- job_name: aggregator
  metrics_path: /metrics
  scrape_interval: "15s"
  scrape_timeout: "10s"
  scheme: http
  follow_redirects: true
  static_configs:
    - targets:
      - 172.18.0.1:5000
